# Generated by Django 4.2.7 on 2023-12-03 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_bill_time_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 2, 21, 14, 926365)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='num_stars',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='num_votes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='rank',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 2, 21, 14, 927376)),
        ),
    ]
