# Generated by Django 4.2.7 on 2023-11-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_manager_sharer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='user',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='sharer',
            old_name='user',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='manager',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
