# Generated by Django 4.2.7 on 2023-11-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_user_manager_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='raw_password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
