# Generated by Django 4.2.7 on 2024-01-01 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_test_alter_bill_time_alter_comment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 11, 16, 44, 813468)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 11, 16, 44, 813468)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 11, 16, 44, 813468)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 11, 16, 44, 804753)),
        ),
    ]
