# Generated by Django 4.2.7 on 2023-12-29 05:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_bill_time_alter_post_time_alter_product_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_post', to='homepage.manager'),
        ),
        migrations.AddField(
            model_name='post',
            name='sharer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.sharer'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 12, 21, 43, 498741)),
        ),
        migrations.AlterField(
            model_name='post',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider', to='homepage.manager'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 12, 21, 43, 498741)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 12, 21, 43, 498741)),
        ),
    ]
