# Generated by Django 4.2.7 on 2023-12-29 09:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_post_manager_post_sharer_alter_bill_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sharer',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='value',
        ),
        migrations.AddField(
            model_name='userlike',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.account'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 16, 22, 18, 515965)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 16, 22, 18, 515965)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 16, 22, 18, 515965)),
        ),
    ]
