# Generated by Django 4.2.7 on 2023-11-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_post_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='manager',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='fullname'),
        ),
    ]
