# Generated by Django 4.2.7 on 2023-11-27 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_bill_product_post_order_image_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dis_like',
            new_name='dislike',
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 19, 40, 1, 315078)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 19, 40, 1, 316078)),
        ),
    ]
