# Generated by Django 4.2.7 on 2023-11-27 13:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_rename_dis_like_post_dislike_alter_bill_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='sharer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.sharer', verbose_name='Người mua'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 20, 3, 22, 36814)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 20, 3, 22, 37814)),
        ),
    ]
