# Generated by Django 4.2.7 on 2023-12-10 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_bill_status_alter_bill_time_alter_post_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 1, 18, 3, 13801)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 1, 18, 3, 13801)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 1, 18, 3, 12797)),
        ),
    ]
