# Generated by Django 4.2.4 on 2023-11-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_bill_time_alter_post_time'),
        ('homepage', '0010_comment_account_alter_bill_time_alter_post_time'),
    ]

    operations = [
    ]
