# Generated by Django 4.2.4 on 2023-11-28 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_manager_bio_alter_bill_time_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 10, 56, 21, 480480)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='bio',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 10, 56, 21, 480480)),
        ),
    ]
