# Generated by Django 4.2.7 on 2023-11-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_bill_time_alter_manager_bio_alter_post_time'),
        ('homepage', '0013_alter_bill_time_alter_post_time'),
    ]

    operations = [
    ]
