# Generated by Django 4.2.7 on 2023-11-28 07:40

import datetime
from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_bill_time_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to=homepage.models.img_path_avt),
        ),
        migrations.AddField(
            model_name='sharer',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to=homepage.models.img_path_avt),
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 14, 40, 9, 557554)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 14, 40, 9, 557554)),
        ),
    ]
