# Generated by Django 4.2.7 on 2023-11-28 08:30

import datetime
from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_manager_avatar_sharer_avatar_alter_bill_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 30, 13, 949784)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='avatar',
            field=models.ImageField(default='noavatar.png', upload_to=homepage.models.img_path_avt),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 30, 13, 949784)),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='avatar',
            field=models.ImageField(default='noavatar.png', upload_to=homepage.models.img_path_avt),
        ),
    ]
