# Generated by Django 4.2.7 on 2023-12-11 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_alter_bill_time_alter_post_time_alter_product_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='name_stripped',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 19, 38, 30, 354371)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 19, 38, 30, 354371)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 19, 38, 30, 354371)),
        ),
    ]
