# Generated by Django 4.2.7 on 2023-12-03 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_alter_bill_time_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='num_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='num_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='rank',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 0, 57, 44, 306483)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 0, 57, 44, 307404)),
        ),
    ]
