# Generated by Django 4.2.7 on 2023-12-11 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_post_name_stripped_product_name_stripped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='area',
            field=models.CharField(choices=[('all', 'All'), ('HaiBaTrung', 'Hai Bà Trưng'), ('ThanhXuan', 'Thanh Xuân'), ('DongDa', 'Đống Đa')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 22, 22, 10, 361380)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 22, 22, 10, 362381)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 22, 22, 10, 361380)),
        ),
    ]
