# Generated by Django 4.2.7 on 2023-12-12 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_image_isdelete_alter_bill_time_alter_post_time_and_more'),
        ('homepage', '0021_manager_area_alter_bill_time_alter_post_time_and_more'),
    ]

    operations = [
    ]
