# Generated by Django 4.2.7 on 2023-12-25 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0033_alter_bill_time_alter_post_time_alter_product_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='ward',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sharer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sharer',
            name='bio',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='sharer',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sharer',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sharer',
            name='ward',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 17, 57, 0, 344909)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 17, 57, 0, 344909)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 17, 57, 0, 344909)),
        ),
    ]
