# Generated by Django 4.2.7 on 2023-12-25 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_manager_city_manager_district_manager_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 18, 15, 15, 445121)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 18, 15, 15, 446121)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 18, 15, 15, 445121)),
        ),
    ]
