# Generated by Django 4.2.7 on 2023-12-25 12:18

import datetime
from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0035_rename_number_manager_phone_alter_bill_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='bank',
            field=models.ImageField(default='noavatar.png', upload_to=homepage.models.img_path_bank),
        ),
        migrations.AddField(
            model_name='manager',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 19, 18, 15, 94405)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 19, 18, 15, 94405)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 19, 18, 15, 93403)),
        ),
    ]
