# Generated by Django 4.2.7 on 2023-12-25 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0036_manager_bank_manager_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 19, 29, 18, 152771)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name_stripped',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 19, 29, 18, 153770)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 19, 29, 18, 152771)),
        ),
    ]
