# Generated by Django 4.2.7 on 2023-12-25 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0037_alter_bill_time_alter_manager_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='t_closed',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AddField(
            model_name='manager',
            name='t_open',
            field=models.TimeField(default='0:00'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 20, 20, 8, 318453)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 20, 20, 8, 319452)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 20, 20, 8, 318453)),
        ),
    ]
