# Generated by Django 4.2.7 on 2023-12-26 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0038_manager_t_closed_manager_t_open_alter_bill_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='area',
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 16, 38, 22, 681487)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 16, 38, 22, 681487)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 16, 38, 22, 680491)),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('food', 'Đồ ăn'), ('bun dau', 'Bún đậu'), ('com rang', 'Cơm rang'), ('nem nuong', 'Nem nướng'), ('cong vien', 'Công viên'), ('bao tang', 'Bảo tàng'), ('service', 'Dịch vụ khác')], max_length=10),
        ),
    ]
