# Generated by Django 4.2.4 on 2023-12-30 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0044_remove_bill_sharer_bill_acc_alter_bill_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 18, 41, 46, 752718)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 18, 41, 46, 752718)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 18, 41, 46, 752718)),
        ),
    ]
