# Generated by Django 4.2.7 on 2023-11-24 17:06

import Homepage1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('vaitro', models.CharField(choices=[('m', 'NguoiQuanLy'), ('u', 'NguoiChiaSe')], max_length=1)),
                ('avatar', models.ImageField(null=True, upload_to=Homepage1.models.image_upload_path)),
            ],
        ),
    ]
