# Generated by Django 4.2.7 on 2023-11-24 19:00

import Homepage1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage1', '0002_alter_taikhoan_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='avatar',
            field=models.ImageField(default='avatar_user/default.png', upload_to=Homepage1.models.image_upload_path),
        ),
    ]
